### ISSUE TITLE
Smartphone got wiped

### ISSUE THREAD

**Issue by anon97945** [mbkore/lockup#1]
Hello,

my smartphone got wiped on the moment i opened 2 times a .py file in nekogramx(a telegram fork) with the app https://play.google.com/store/apps/details?id=com.rhmsoft.code&hl=gsw&gl=US

Cant provide any logs due to wipe.

Im using Blackview BV9700 Pro with Android 9 Security Patch 5. August 2019

**Comment by levlesec** [comment]
Hello,

I don't plan on supporting this code base (I will review and accept pull requests
from others) but I can probably give you some guidance. Make sure your device is 
connected to your system via USB and that you are running logcat when testing 
the application.

```
adb logcat
```

I believe I removed most (if not all) calls to Log.d() but during development I
relied on this heavily. The phone will be wiped and logs would be lost locally
but the same information will be available in your terminal. I hope this helps.
